export const CCC_CAMPAIGN_REQUEST_BUDGET_EXHAUSTED_CODE =
  "CCC_CAMPAIGN_REQUEST_BUDGET_EXHAUSTED" as const;

export const CCC_CAMPAIGN_REQUEST_BUDGET_EXHAUSTED_REASON =
  `ccc-permanent:${CCC_CAMPAIGN_REQUEST_BUDGET_EXHAUSTED_CODE}` as const;

export const CCC_PRD_REQUEST_BUDGET_BELOW_PROVIDER_TASK_FLOOR =
  "CCC_PRD_REQUEST_BUDGET_BELOW_PROVIDER_TASK_FLOOR" as const;
